[package]
name = "cargo-fusion"
version = "0.1.0"
edition = "2024"

[dependencies]
clap.workspace = true
anyhow.workspace = true
cargo_metadata.workspace = true
cargo-manifest.workspace = true
zip.workspace = true
walkdir.workspace = true
