[package]
name = "cargo-fusion"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
anyhow.workspace = true
cargo_metadata.workspace = true
cargo-manifest.workspace = true
zip.workspace = true
walkdir.workspace = true
