name = "Example"
version = "0.0.1"
description = "Example"
repository = "..."
authors = [
    { name = "Irisu", email = "mrapacheee@gmail.com" }
]

capabilities = ["general.graphics", "net.socket.tcp", "net.socket.udp"]

#custom = ["message", "test"]

[errors]
0 = {name = "I/O Error", description = "Description"}
1 = {name = "Access denied", description = "Description"}
